<?php

namespace Spb\RealityBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Spb\RealityBundle\Entity\Search\FlatSearch;

/**
 * FlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlatRepository extends EntityRepository
{
    public function buildSearchQuery(FlatSearch $fs)
    {
        $qb = $this->createQueryBuilder('r');
               
        //Мин. цена на объект недвижимости
        if ($fs->min_price) $qb->andWhere($qb->expr()->gte('r.price', $fs->min_price));
        
        return $qb->getQuery();
    }
}