parameters:
    spb_reality.rss_parser.class: Spb\RealityBundle\Services\RssNews

services:
#    spb_reality.example:
#        class: %spb_reality.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    rss_parser:
        class: %spb_reality.rss_parser.class%