parameters:
#    spb_reality.example.class: Spb\RealityBundle\Example

services:
#    spb_reality.example:
#        class: %spb_reality.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    flat_search:
        class:        SpbRealityBundle\Form\Search\FlatSearchType
        arguments:    [doctrine]